version: 2.1

jobs:
  backend-build:
    docker:
      - image: cimg/node:20.2
    steps:
      - checkout
      - run:
          name: Install Dependencies for Backend
          command: |
            cd BACKEND
            npm install
      - run:
          name: Build Backend
          command: |
            cd BACKEND
            npm run build

  frontend-build:
    docker:
      - image: cimg/node:20.2
    steps:
      - checkout
      - run:
          name: Install Dependencies for Frontend
          command: |
            cd secure-payments-portal
            npm install
      - run:
          name: Build Frontend
          command: |
            cd secure-payments-portal
            npm run build

  sonar-scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=Team-CJR-VC_APDSPOE \
              -Dsonar.sources=. \
              -Dsonar.host.url=${SONAR_HOST_URL} \
              -Dsonar.login=${SONAR_TOKEN}

workflows:
  version: 2
  build-workflow:
    jobs:
      - backend-build
      - frontend-build
      - sonar-scan:
          requires:
            - backend-build
            - frontend-build
