version: 2.1

jobs:
  backend-tests:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies for Backend
          command: |
            cd BACKEND
            npm install

  frontend-tests:
    docker:
      - image: cimg/node:20.2
    steps:
      - checkout
      - run:
          name: Install Dependencies for Frontend
          command: |
            cd secure-payments-portal
            npm install

workflows:
  version: 2
  test-workflow:
    jobs:
      - backend-tests
      - frontend-tests