version: 2.1

# Define the jobs to be used in workflows
jobs:
  # Job to set up Node.js environment and run tests
  build-and-test:
    docker:
      - image: circleci/node:16  # Use a Node.js Docker image
    steps:
      - checkout  # Check out the code from the repository

      - run:
          name: Install Dependencies
          command: npm install  # Install dependencies

      - run:
          name: Lint the code
          command: npm run lint  # Run linter

      - run:
          name: Run Tests
          command: npm test  # Run your tests

  # Job to deploy the project (assuming you are deploying to a server)
  deploy:
    docker:
      - image: circleci/node:16
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Build the Project
          command: npm run build  # Assuming you have a build command

      - run:
          name: Deploy
          command: |
            echo "Deploying the project..."
            # Add deployment commands here, like SSH to server and deploy, or deploy to a service like Heroku/AWS

# Workflows orchestrate jobs
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test  # Deploy only after tests pass